services:
    postgres:
        image: ankane/pgvector # Uses a prebuilt PostgreSQL with pgvector
        container_name: rag-chatbot
        environment:
            POSTGRES_USER: marco
            POSTGRES_PASSWORD: password
            POSTGRES_DB: chatbot-db
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    pg_data:
