"""add_summary_column

Revision ID: 50e2a3df75f1
Revises: 
Create Date: 2025-05-11 18:00:33.026994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50e2a3df75f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('embeddings_index_basic', table_name='chunk', postgresql_using='hnsw')
    op.drop_index('ix_chunk_vid_id', table_name='chunk')
    op.drop_table('chunk')
    op.add_column('vid_chat', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vid_chat', 'summary')
    op.create_table('chunk',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('vid_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chunk_pkey')
    )
    op.create_index('ix_chunk_vid_id', 'chunk', ['vid_id'], unique=False)
    op.create_index('embeddings_index_basic', 'chunk', ['embedding'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
